[project]
name = "lutris-art-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inquirer>=2.10.0",
    "requests>=2.27.1",
]
